name: GitHub Actions

on:
  pull_request:
    branches: ["dev"]
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    - name: Setuping Node 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: npm
    - name: Install
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Run eslint
      run: npm run eslint
    - name: Run prettier
      run: npm run prettier
