name: GitHub Actions

on:
  pull_request:
    branches: ["dev"]
    types: [opened, reopened]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - name: Init testing
      uses: actions/checkout@v2
    - run: echo "🤡 Let`s test this pr"
    - name: Use Node.js 16
      with:
        node-version: "16"
        cache: "npm"
    - name: Install
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Run eslint
      run: npm run eslint
    - name: Run prettier
      run: npm run prettier
